### ISSUE TITLE
App not running

### ISSUE THREAD

**Issue by jaexplorer** [bradtraversy/simple-electron-react#1]
![Screen Shot 2020-05-23 at 3 58 34 pm](https://user-images.githubusercontent.com/20828446/82722998-b7625800-9d0e-11ea-82f2-1e80f15d8954.png)
![Screen Shot 2020-05-23 at 3 58 46 pm](https://user-images.githubusercontent.com/20828446/82722999-baf5df00-9d0e-11ea-8d54-94496b8c92d5.png)

Hi Brad, 
Cloned this repo, ran npm install, then npm start and I keep getting these errors. I'm not sure what the problem is?

**Comment by jaexplorer** [comment]
Sorry Brad, after 2 hours. Tried again, now it compiles, I don't know why.

**Comment by bradtraversy** [comment]
That's strange, not sure why it failed. Hopefully, it was just some kind of fluke. Let me know if it happens again
